name: Build and Deploy to Prod Server

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Make .env.local
        run: |
          touch ./client/.env.local
          echo "${{ secrets.ENV_PROD }}" > ./client/.env.local
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: client/prod/ai-canvas
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          cd client
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        id: deploy-ec2
        with:
          host: ${{ secrets.AWS_PROD_HOST }}
          username: ${{ secrets.AWS_PROD_USERNAME }}
          key: ${{ secrets.AWS_PROD_SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            cd shell
            sh deploy-client.sh
